### PR TITLE
supporting the result of universal enrichment analyzer by setting orgDb to NULL

### PR DESCRIPTION
**Pull request by xiangpin**
+ The `clusterProfiler` provided a universal enrichment function `enricher`, which was inherited by the `MicrobiomeProfiler`. But the original functions of `CBNplot`  do not support the results. This `PR` fixes the problem by setting `orgDb` to `NULL`.

```
library(MicrobiomeProfiler)
data(Rat_data)
ko.res <- enrichKO(Rat_data)
exp.dat <- matrix(abs(rnorm(910)), 91, 10) %>% magrittr::set_rownames(value=Rat_data) %>% magrittr::set_colnames(value=paste0('S', seq_len(ncol(.))))
exp.dat %>% head
library(CBNplot)
bngeneplot(ko.res, exp=exp.dat, pathNum=1, orgDb=NULL)
```
xx

### CODE REVIEW

**Comment by noriakis** [comment]
@xiangpin I sincerely appreciate the important fix for the package and merged the request.

**Comment by noriakis** [comment]
@xiangpin Thank you for the recent PR. If it is okay with you, may I present a described example using MicrobiomeProfiler in the README with the appropriate credits?

**Comment by xiangpin** [comment]
Yes, sure

**Comment by noriakis** [comment]
Thank you for your reply, and I appreciate your permission. I will update README.

**Pull request merged**
